/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const QualificationForm = IDL.Record({
  'age' : IDL.Text,
  'primaryGoal' : IDL.Text,
  'profession' : IDL.Text,
  'fullName' : IDL.Text,
  'submittedAt' : IDL.Int,
  'biggestChallenge' : IDL.Text,
  'companyName' : IDL.Text,
  'annualTurnover' : IDL.Text,
  'industry' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAllQualificationForms' : IDL.Func(
      [],
      [IDL.Vec(QualificationForm)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitQualificationForm' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const QualificationForm = IDL.Record({
    'age' : IDL.Text,
    'primaryGoal' : IDL.Text,
    'profession' : IDL.Text,
    'fullName' : IDL.Text,
    'submittedAt' : IDL.Int,
    'biggestChallenge' : IDL.Text,
    'companyName' : IDL.Text,
    'annualTurnover' : IDL.Text,
    'industry' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAllQualificationForms' : IDL.Func(
        [],
        [IDL.Vec(QualificationForm)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitQualificationForm' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };